//
//  question-2.c
//  
//
//  Created by Andre Pitombeira on 22/08/15.
//

/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

int main(void) {
    int limit = 4000000;
    int num1 = 1;
    int num2 = 1;
    int temp = 0;
    int sum = 0;
    
    while (num2 < limit) {
        if (num2 % 2 == 0) {
            sum += num2;
        }
        
        temp = num1 + num2;
        num1 = num2;
        num2 = temp;
    }
    
    printf("%d\n", sum);
}
